# Generated by Django 5.0 on 2025-12-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelie',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='cep',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='rua',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='atelie',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='endereco',
            field=models.CharField(blank=True, help_text='Campo mantido para compatibilidade. Use os campos específicos acima.', max_length=300, verbose_name='Endereço (Campo Legado)'),
        ),
    ]
