# Generated by Django 5.0 on 2025-12-10 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_atelie_bairro_atelie_cep_atelie_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelie',
            options={'verbose_name': 'AteliÇ¦', 'verbose_name_plural': 'AteliÇ¦s'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'UsuÇ\xadrio', 'verbose_name_plural': 'UsuÇ\xadrios'},
        ),
        migrations.AddField(
            model_name='pessoaperfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoaperfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoaperfil',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='NÇ§mero'),
        ),
        migrations.AddField(
            model_name='pessoaperfil',
            name='rua',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='cep',
            field=models.CharField(blank=True, help_text='Apenas nÇ§meros', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='endereco',
            field=models.CharField(blank=True, help_text='Campo mantido para compatibilidade. Use os campos especÇðficos acima.', max_length=300, verbose_name='EndereÇõo (Campo Legado)'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='especialidades',
            field=models.TextField(help_text='Descreva as especialidades do ateliÇ¦', verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='NÇ§mero'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='telefone_comercial',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: DDXXXXXXXXX (DDD + 9 dÇðgitos)', regex='^\\d{2}9\\d{8}$')], verbose_name='Telefone Comercial'),
        ),
        migrations.AlterField(
            model_name='atelie',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_atelie': True}, on_delete=django.db.models.deletion.CASCADE, related_name='atelie', to=settings.AUTH_USER_MODEL, verbose_name='UsuÇ\xadrio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_atelie',
            field=models.BooleanField(default=False, verbose_name='Ç% AteliÇ¦'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='Ç% Cliente'),
        ),
        migrations.AlterField(
            model_name='pessoaperfil',
            name='cep',
            field=models.CharField(blank=True, help_text='Apenas nÇ§meros', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoaperfil',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='EndereÇõo (Campo Legado)'),
        ),
        migrations.AlterField(
            model_name='pessoaperfil',
            name='telefone',
            field=models.CharField(help_text='Formato: DDXXXXXXXXX (apenas nÇ§meros)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: DDXXXXXXXXX (DDD + 9 dÇðgitos)', regex='^\\d{2}9\\d{8}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoaperfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='UsuÇ\xadrio'),
        ),
    ]
