# Generated by Django 5.0 on 2025-11-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Descrição do look/peça desejada', verbose_name='Prompt')),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='gerados/%Y/%m/%d/', verbose_name='Arquivo')),
                ('url_arquivo', models.URLField(blank=True, null=True, verbose_name='URL do Arquivo')),
                ('modelo', models.CharField(default='dall-e-3', help_text='Modelo de IA utilizado para gerar a imagem', max_length=100, verbose_name='Modelo de IA')),
                ('parametros_json', models.JSONField(blank=True, default=dict, help_text='Parâmetros adicionais da geração (tamanho, estilo, etc.)', verbose_name='Parâmetros')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Prompt de Imagem',
                'verbose_name_plural': 'Prompts de Imagens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
