# Generated by Django 5.0 on 2025-11-03 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelie', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atelie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.atelie', verbose_name='Ateliê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='atelie.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='atelie.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='estoqueitem',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='atelie.produto', verbose_name='Produto'),
        ),
    ]
