# Generated by Django 5.0 on 2025-11-27 00:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0003_servicos_agendamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_servico', to='atelie.servico', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_estimada',
            field=models.IntegerField(blank=True, help_text='Informe em minutos (opcional)', null=True, verbose_name='Duração Estimada (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Base'),
        ),
    ]
