# Generated by Django 5.0 on 2025-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0006_add_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_ORCAMENTO', 'Aguardando Orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('ORCAMENTO_REPROVADO', 'Orçamento Reprovado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_RETIRADA', 'Aguardando Retirada'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_ORCAMENTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_servico',
            field=models.CharField(choices=[('CRIANCAO', 'Criação de look / peça'), ('AJUSTES', 'Ajustes'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Serviço'),
        ),
    ]
