# Generated by Django 5.0 on 2025-11-27 15:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0007_alter_pedido_status_alter_pedido_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('ESTOQUE', 'Produtos em estoque'), ('PERSONALIZADO', 'Pedido personalizado')], default='ESTOQUE', max_length=20, verbose_name='Tipo de Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Orçamento'),
        ),
    ]
