# Generated by Django 5.0 on 2025-11-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0008_pedido_tipo_pedido_pedido_valor_orcamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_orcamento',
        ),
    ]
