# Generated by Django 5.0 on 2025-12-11 02:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0009_remove_pedido_tipo_pedido_and_more'),
        ('usuarios', '0004_alter_atelie_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Servico', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='descricao_cliente',
            field=models.TextField(blank=True, verbose_name='Descricao do pedido (cliente)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_orcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor orcado'),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='lida_por_atelie',
            field=models.BooleanField(default=False, verbose_name='Lida pelo atelie'),
        ),
        migrations.AlterField(
            model_name='estoqueitem',
            name='ponto_reposicao',
            field=models.IntegerField(default=5, help_text='Quantidade minima antes de alertar sobre reposicao', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ponto de Reposicao'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preco unitario'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_servico', to='atelie.servico', verbose_name='Servico'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='atelie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.atelie', verbose_name='Atelie'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_agendada',
            field=models.DateField(blank=True, null=True, verbose_name='Data do agendamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_agendada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do agendamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_ORCAMENTO', 'Aguardando orcamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('ORCAMENTO_REPROVADO', 'Orcamento reprovado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_RETIRADA', 'Aguardando retirada'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_ORCAMENTO', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_servico',
            field=models.CharField(choices=[('CRIANCAO', 'Criacao de look / peca'), ('AJUSTES', 'Ajustes'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de servico'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('VESTIDO', 'Vestido'), ('SAIA', 'Saia'), ('BLUSA', 'Blusa'), ('CALCA', 'Calca'), ('CONJUNTO', 'Conjunto'), ('ACESSORIO', 'Acessorio'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preco Base'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_estimada',
            field=models.IntegerField(blank=True, help_text='Informe em minutos (opcional)', null=True, verbose_name='Duracao Estimada (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preco Base'),
        ),
    ]
