# Generated by Django 5.0 on 2025-12-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelie', '0010_alter_servico_options_pedido_descricao_cliente_and_more'),
        ('usuarios', '0004_alter_atelie_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='atelie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.atelie', verbose_name='Atelie'),
        ),
        migrations.AddField(
            model_name='servico',
            name='atelie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='usuarios.atelie', verbose_name='Atelie'),
        ),
    ]
